# Local environment configuration using docker-compose
# api service 사용시 LocalConfig -> $SQLALCHEMY_DATABASE_URI 주석 해제

version: '3.7'

volumes:
  tanos_db_local: {}

services:
#  redis:
#    image: redis:latest
#    container_name: redis
#    ports:
#      - 6379:6379
#    restart: always

#  postgres:
#    image: postgres
#    container_name: tanos-postgres
#    volumes:
#      - tanos_db_local:/var/lib/postgresql/data
#    ports:
#      - "5432:5432"
#    environment:
#      - POSTGRES_DB=tanos
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=1234
#      - POSTGRES_INITDB_ARGS=--encoding=UTF-8

#  worker:
#      build: .
#      container_name: worker
#      restart: always
#      command: "celery -A celery_app.celery worker -B --loglevel=info"
#      # command: "celery -A celery_app.celery worker -B --loglevel=info --without-mingle -P solo -l info -E --concurrency=1 -Ofair"
#      depends_on:
#        - redis

  prometheus:
      image: prom/prometheus
      container_name: prometheus
      restart: always
      volumes:
        - ./prometheus/:/etc/prometheus/
      command:
        - '--config.file=/etc/prometheus/prometheus.yml'
      ports:
        - 9090:9090

  flower:
    image: mher/flower
    container_name: flower
    environment:
      - CELERY_BROKER_URL=redis://127.0.0.1:6379
      - FLOWER_PORT=7777
    ports:
      - 7777:7777

  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: always
    depends_on:
      - prometheus
    ports:
      - "3000:3000"