openapi: "3.0.2"
tags:
  - Notification
security:
  - userAuth: []
parameters:
  - name: category
    in: query
    required: true
    description: official or my
    schema:
      type: string
      example: official
responses:
  '200':
    description:
    content:
      application/json:
        schema:
          properties:
            data:
              type: object
              properties:
                messages:
                  type: array
                  items:
                    type: object
                    properties:
                      category:
                        type: string
                        example: official
                      created_date:
                        type: string
                        example: 20210701
                      diff_min:
                        type: string
                        example: 1500000
                      is_read:
                        type: boolean
                        example: False
                      title:
                        type: string
                        example: 분양일정
                      content:
                        type: string
                        example: 관심 설정 해두신 동탄 메르시 분양이 시작됐습니다.
                      data:
                        type: object
                        properties:
                          id:
                            type: integer
                            example: 1
                          user_id:
                            type: integer
                            example: 1
                          topic:
                            type: string
                            example: "apt002"
  '400':
    description: invalid_request_error
    content:
      application/json:
        schema:
          $ref: '#/components/schemas/invalid_request_error'
  '401':
    description: unauthorized_error
    content:
      application/json:
        schema:
          $ref: '#/components/schemas/unauthorized_error'
  '404':
    description: not_found_error
    content:
      application/json:
        schema:
          $ref: '#/components/schemas/user_not_found_error'
  '500 #1':
    description: internal_server_error
    content:
      application/json:
        schema:
          $ref: '#/components/schemas/internal_server_error'
  '500 #2':
    description: internal_server_error
    content:
      application/json:
        schema:
          $ref: '#/components/schemas/response_schema_validation_error'