version: "3"
services:
  prod-tanos-cron:
    image: __ECR_ADDRESS__
    ports:
      - "5000:5000"
    command: "newrelic-admin run-program supervisord"
    logging:
      driver: awslogs
      options:
        awslogs-group: toadhome/prod-tanos-cron-logs
        awslogs-region: ap-northeast-2
        awslogs-stream-prefix: toadhome/prod-tanos-cron-logs
        awslogs-create-group: "true"
    environment:
      # environment