version: 1
task_definition:
  task_execution_role: ecsTaskExecutionRole
  ecs_network_mode: awsvpc
  task_size:
    cpu_limit: 1024
    mem_limit: 2GB
  services:
    prod-tanos-api:
      cpu_shares: 700
      mem_limit: 1.5GB
run_params:
  network_configuration:
    awsvpc_configuration:
      subnets:
        - "subnet-0a54154b0e29a1ceb"
        - "subnet-08380a16443dd2eab"
      security_groups:
        - "sg-0cdc3572ba24ae0dc"
      assign_public_ip: DISABLED