"""create user_status_logs table

Revision ID: 24b8fa736f0f
Revises: 4a93dd41716d
Create Date: 2021-04-30 23:25:42.004953

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "24b8fa736f0f"
down_revision = "4a93dd41716d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_status_logs",
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("status", sa.String(length=10), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_status_logs")
    # ### end Alembic commands ###
