"""recently_view_tables

Revision ID: 2b39ceec2fb5
Revises: da750a6dd84b
Create Date: 2021-07-21 17:13:28.242204

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "2b39ceec2fb5"
down_revision = "da750a6dd84b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "recently_views",
        sa.Column(
            "id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("house_id", sa.BigInteger(), nullable=False),
        sa.Column("type", sa.SmallInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"],),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column(
        "public_sale_details",
        sa.Column("area_type", sa.String(length=5), nullable=True),
    )
    op.add_column(
        "public_sales",
        sa.Column("offer_notice_url", sa.String(length=100), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("public_sales", "offer_notice_url")
    op.drop_column("public_sale_details", "area_type")
    op.drop_table("recently_views")
    # ### end Alembic commands ###
