"""create_private_sale_detail_tables

Revision ID: 38ad1196e6a1
Revises: 2b39ceec2fb5
Create Date: 2021-07-21 22:56:30.636017

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "38ad1196e6a1"
down_revision = "2b39ceec2fb5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "private_sale_details",
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("private_sales_id", sa.BigInteger(), nullable=False),
        sa.Column("private_area", sa.Float(), nullable=False),
        sa.Column("supply_area", sa.Float(), nullable=False),
        sa.Column("contract_date", sa.String(length=8), nullable=True),
        sa.Column("deposit_price", sa.Integer(), nullable=False),
        sa.Column("rent_price", sa.Integer(), nullable=False),
        sa.Column("trade_price", sa.Integer(), nullable=False),
        sa.Column("floor", sa.SmallInteger(), nullable=False),
        sa.Column(
            "trade_type",
            postgresql.ENUM(
                "매매", "전세", "월세", name="realtradetypeenum", create_type=False
            ),
            nullable=False,
        ),
        sa.Column("is_available", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["private_sales_id"], ["private_sales.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column(
        "private_sales", sa.Column("name", sa.String(length=50), nullable=True)
    )
    op.drop_column("private_sales", "private_area")
    op.drop_column("private_sales", "contract_date")
    op.drop_column("private_sales", "deposit_price")
    op.drop_column("private_sales", "trade_price")
    op.drop_column("private_sales", "supply_area")
    op.drop_column("private_sales", "trade_type")
    op.drop_column("private_sales", "floor")
    op.drop_column("private_sales", "is_available")
    op.drop_column("private_sales", "rent_price")
    op.alter_column(
        "public_sale_details",
        "area_type",
        existing_type=sa.VARCHAR(length=5),
        nullable=True,
    )
    # ### end Alembic commands ###
    # with open("./migrations/seeds/default_houses.sql") as fp:
    #     op.execute(fp.read())


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "public_sale_details",
        "area_type",
        existing_type=sa.VARCHAR(length=5),
        nullable=True,
    )
    op.add_column(
        "private_sales",
        sa.Column("rent_price", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "private_sales",
        sa.Column("is_available", sa.BOOLEAN(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "private_sales",
        sa.Column("floor", sa.SMALLINT(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "private_sales",
        sa.Column(
            "trade_type",
            postgresql.ENUM("매매", "전세", "월세", name="realtradetypeenum"),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "private_sales",
        sa.Column(
            "supply_area",
            postgresql.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "private_sales",
        sa.Column("trade_price", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "private_sales",
        sa.Column("deposit_price", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "private_sales",
        sa.Column(
            "contract_date", sa.VARCHAR(length=8), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "private_sales",
        sa.Column(
            "private_area",
            postgresql.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_column("private_sales", "name")
    op.drop_table("private_sale_details")
    # ### end Alembic commands ###
