"""create_house_public_detail_photos

Revision ID: da750a6dd84b
Revises: 65261925d8fa
Create Date: 2021-07-16 17:39:21.489045

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "da750a6dd84b"
down_revision = "65261925d8fa"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "public_sale_detail_photos",
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("public_sale_details_id", sa.BigInteger(), nullable=False),
        sa.Column("file_name", sa.String(length=20), nullable=False),
        sa.Column("path", sa.String(length=150), nullable=False),
        sa.Column("extension", sa.String(length=4), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["public_sale_details_id"], ["public_sale_details.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("public_sale_details_id"),
    )
    op.drop_column("devices", "endpoint")
    # ### end Alembic commands ###

    op.create_index(
        "administrative_name_gin_varchar_idx",
        "administrative_divisions",
        ["name"],
        unique=False,
        postgresql_using="btree",
    )
    op.create_index(
        "administrative_name_gin_ts_idx",
        "administrative_divisions",
        ["name_ts"],
        unique=False,
        postgresql_using="gin",
    )

    op.create_index(
        "public_sales_name_gin_varcher_idx",
        "public_sales",
        ["name"],
        unique=False,
        postgresql_using="btree",
    )
    op.create_index(
        "public_sales_name_gin_ts_idx",
        "public_sales",
        ["name_ts"],
        unique=False,
        postgresql_using="gin",
    )

    op.create_index(
        "jubun_address_gin_varchar_idx",
        "real_estates",
        ["jibun_address"],
        unique=False,
        postgresql_using="btree",
    )
    op.create_index(
        "jubun_address_gin_ts_idx",
        "real_estates",
        ["jibun_address_ts"],
        unique=False,
        postgresql_using="gin",
    )

    op.create_index(
        "road_address_gin_varchar_idx",
        "real_estates",
        ["road_address"],
        unique=False,
        postgresql_using="btree",
    )
    op.create_index(
        "road_address_gin_ts_idx",
        "real_estates",
        ["road_address_ts"],
        unique=False,
        postgresql_using="gin",
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "devices",
        sa.Column(
            "endpoint",
            sa.VARCHAR(length=100),
            server_default=sa.text("NULL::character varying"),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_table("public_sale_detail_photos")
    # ### end Alembic commands ###
