openapi: "3.0.2"
tags:
  - Report
security:
  - userAuth: []
responses:
  '200':
    description: survey_step=0(미진행), 1(1단계설문중), 2(2단계설문중), 3(설문완료)
    content:
      application/json:
        schema:
          properties:
            data:
              type: object
              properties:
                analysis_text:
                  type: str
                  example: (1) 지역 Hans님은 서울시/부산시 거주자이십니다. 주택청약시 해당...
                user:
                  type: object
                  properties:
                    nickname:
                      type: string
                      example: veronica
                    age:
                      type: integer
                      example: 31
                    survey_step:
                      type: integer
                      example: 3
                    is_ticket_usage_for_user:
                      type: bool
                      example: true
                survey_result:
                  type: object
                  properties:
                    total_point:
                      type: integer
                      example: 32
                    detail_point_house:
                      type: integer
                      example: 21
                    detail_point_family:
                      type: integer
                      example: 21
                    detail_point_bank:
                      type: integer
                      example: 21
                    public_newly_married:
                      type: integer
                      example: 21
                    public_first_life:
                      type: integer
                      example: 21
                    public_multiple_children:
                      type: integer
                      example: 21
                    public_old_parent:
                      type: integer
                      example: 21
                    public_agency_recommend:
                      type: integer
                      example: 21
                    public_normal:
                      type: integer
                      example: 21
                    private_newly_married:
                      type: integer
                      example: 21
                    private_first_life:
                      type: integer
                      example: 21
                    private_multiple_children:
                      type: integer
                      example: 21
                    private_old_parent:
                      type: integer
                      example: 21
                    private_agency_recommend:
                      type: integer
                      example: 21
                    private_normal:
                      type: integer
                      example: 21
                    hope_town_phase_one:
                      type: integer
                      example: 21
                    hope_town_phase_two:
                      type: integer
                      example: 21
                    public_newly_married_div:
                      type: string
                      example: 우선
                    private_newly_married_div:
                      type: string
                      example: 잔여
                    public_first_life_div:
                      type: string
                      example: 우선
                    private_first_life_div:
                      type: string
                      example: 잔여
                    public_married_income_point:
                      type: integer
                      example: 1
                    public_married_child_point:
                      type: integer
                      example: 1
                    public_married_address_point:
                      type: integer
                      example: 1
                    public_married_bank_point:
                      type: integer
                      example: 1
                    public_married_date_point:
                      type: integer
                      example: 1
                    private_married_child_num:
                      type: integer
                      example: 1
                    private_married_rank:
                      type: integer
                      example: 1
                    hope_one_income_point:
                      type: integer
                      example: 1
                    hope_one_address_point:
                      type: integer
                      example: 1
                    hope_one_bank_point:
                      type: integer
                      example: 1
                    hope_two_child_point:
                      type: integer
                      example: 1
                    hope_two_household_point:
                      type: integer
                      example: 1
                    hope_two_address_point:
                      type: integer
                      example: 1
                    hope_two_bank_point:
                      type: integer
                      example: 1
                user_infos:
                  type: array
                  items:
                    type: object
                    properties:
                      code:
                        type: integer
                        example: 1000
                      value:
                        type: string
                        example: noah
  '400':
    description: invalid_request_error
    content:
      application/json:
        schema:
          $ref: '#/components/schemas/invalid_request_error'
  '401':
    description: unauthorized_error
    content:
      application/json:
        schema:
          $ref: '#/components/schemas/unauthorized_error'
  '404 #1':
    description: not_found_error
    content:
      application/json:
        schema:
          $ref: '#/components/schemas/user_not_found_error'
  '404 #2':
    description: not_found_error
    content:
      application/json:
        schema:
          properties:
            detail:
              type: string
              example: survey_result
            message:
              type: string
              example: not_found_error
  '500 #1':
    description: internal_server_error
    content:
      application/json:
        schema:
          $ref: '#/components/schemas/internal_server_error'
  '500 #2':
    description: internal_server_error
    content:
      application/json:
        schema:
          $ref: '#/components/schemas/response_schema_validation_error'