openapi: "3.0.2"
tags:
  - User
security:
  - userAuth: []
requestBody:
  required: true
  content:
    multipart/form-data:
      schema:
        type: object
        required:
          - id
          - email
          - gender
          - nickname
        properties:
          id:
            type: integer
            example: 1
          nickname:
            type: string
            example: Tester
          email:
            type: string
            example: test@gmail.com
          birthday:
            type: string
            example: 19850509
          gender:
            type: string
            example: F
          region_ids:
            type: string
            description: List[Integer]
            example: "[1,2,3]"
          files:
            type: string
            format: binary
responses:
  '200':
    description: A user object
    content:
      application/json:
        schema:
          $ref: '#/components/schemas/create_user'
  '400':
    description: unauthorized_error, invalid_request_error, not_found_error
    content:
      application/json:
        schema:
          $ref: '#/components/schemas/error'