openapi: "3.0.2"
tags:
  - User
security:
  - userAuth: []
parameters:
  - name: user_id
    in: path
    required: true
    description: user id
    schema:
      type: integer
      format: int64
      minimum: 1
responses:
  '200':
    description: A user object
    content:
      application/json:
        schema:
          type: object
          properties:
            id:
              type: integer
              example: 1
            nickname:
              type: string
              example: Simon
  '400':
    description: unauthorized_error, invalid_request_error, not_found_error
    content:
      application/json:
        schema:
          type: object
          properties:
            error_message:
              type: string
              example: ""
            type:
              type: string
              example: unauthorized_error