openapi: "3.0.2"
tags:
  - User
security:
  - userAuth: []
requestBody:
  required: true
  description: codes는 integer / values는 string
  content:
    application/json:
      schema:
        type: object
        required:
          - codes
        properties:
          codes:
            type: array
            items:
              type: integer
              example: 1002, 1003
          values:
            type: array
            items:
              type: string
              example: 11, 11010
responses:
  '200':
    description:
    content:
      application/json:
        schema:
          type: object
          properties:
            data:
              type: object
              items:
                type: integer
                example: 1002, 1003
  '400':
    description: invalid_request_error
    content:
      application/json:
        schema:
          $ref: '#/components/schemas/invalid_request_error'
  '401':
    description: unauthorized_error
    content:
      application/json:
        schema:
          $ref: '#/components/schemas/unauthorized_error'
  '404':
    description: not_found_error
    content:
      application/json:
        schema:
          $ref: '#/components/schemas/user_not_found_error'
  '500 #1':
    description: internal_server_error
    content:
      application/json:
        schema:
          $ref: '#/components/schemas/internal_server_error'
  '500 #2':
    description: internal_server_error
    content:
      application/json:
        schema:
          $ref: '#/components/schemas/response_schema_validation_error'