openapi: "3.0.2"
tags:
  - Post
security:
  - userAuth: []
parameters:
  - name: post_category
    in: query
    required: true
    description: notice(1), faq(2)
    schema:
      type: integer
      example: 1
  - name: previous_post_id
    in: query
    required: false
    description: null(처음 글 진입시) or 10(페이지 더 넘길때 마지막 post_id = response.meta의 last_post_id)
    schema:
      type: integer
      example: null
responses:
  '200':
    description: get post list
    content:
      application/json:
        schema:
          properties:
            data:
              type: object
              properties:
                posts:
                  type: array
                  items:
                    $ref: '#/components/schemas/post'
            meta:
              $ref: '#/components/schemas/post_meta'

  '400':
    description: unauthorized_error, invalid_request_error, not_found_error, system_error
    content:
      application/json:
        schema:
          $ref: '#/components/schemas/error'
